---
- name: put my.cnf
  template:
    src=slave.j2
    dest=/etc/my.cnf
  register: last_result


- name: restart mysql
  service:
    name=mysql
    state=restarted
    sleep=5

- mysql_user:
    login_user: root
    login_password: 7layer
    name: "{{ mysql_repl_user }}"
    host_all: "yes"
    state: absent


- name: create replication user ON MASTER {{ mysql_repl_master }}
  mysql_user:
    name={{ mysql_repl_user }}
    password={{ mysql_repl_pass }}
    host={{ mysql_repl_master }}
    priv="*.*:REPLICATION SLAVE,REPLICATION CLIENT"

- name: Reload privilege tables
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - FLUSH PRIVILEGES

- name: Check master replication status.
  mysql_replication: mode=getmaster
  delegate_to: "{{ mysql_repl_master }}"
  register: master 
#
#
##### Stop mysql slave thread
- mysql_replication:
    mode: stopslave

##### reset mysql slave thread
#- mysql_replication:
#    mode: resetslave
#
- name: Configure replication on the master {{ mysql_repl_master }}.
  mysql_replication:
   mode: changemaster
   master_host: "{{ mysql_repl_master }}"
   master_user: "{{ mysql_repl_user }}"
   master_password: "{{ mysql_repl_pass }}"
   master_port:  3307 
   master_log_file: "{{ master.File }}"
   master_log_pos: "{{ master.Position }}"
  ignore_errors: True
#   master_log_file: ""
#   master_log_pos:  0
#
###### Start mysql slave thread
- mysql_replication:
    mode: startslave
#
