---
- name: put my.cnf
  template:
    src=master.j2
    dest=/etc/my.cnf
  register: last_result


- name: restart mysql
  service:
    name=mysql
    state=restarted
    sleep=1
 
- mysql_user:
    login_user: root
    login_password: 7layer
    name: "{{ mysql_repl_user }}"
    host_all: "yes"
    state: absent



- name: create replication user {{ mysql_repl_user }}
  mysql_user:
    name={{ mysql_repl_user }}
    password={{ mysql_repl_pass }}
    host={{ mysql_repl_slave }}
    priv="*.*:REPLICATION SLAVE,REPLICATION CLIENT"


- name: Reload privilege tables
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - FLUSH PRIVILEGES

- name: Check master replication status.
  mysql_replication: mode=getmaster
  delegate_to: "{{ mysql_repl_slave }}"
  register: slave

### Stop mysql slave thread
- mysql_replication:
    mode: stopslave

### reset mysql slave thread
#- mysql_replication:
#    mode: resetslave

- name: Configure replication on the slave.
  mysql_replication:
   mode: changemaster
   master_host: "{{ mysql_repl_slave }}"
   master_user: "{{ mysql_repl_user }}"
   master_password: "{{ mysql_repl_pass }}"
   master_port: 3307
   master_log_file: "{{ slave.File }}"
   master_log_pos: "{{ slave.Position }}"
  ignore_errors: True
#   master_log_file: "" 
#   master_log_pos:  0
#
#### Start mysql slave thread
- mysql_replication:
    mode: startslave
## 
